### ISSUE TITLE
Coding Conventions

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#12]
Hi @ivamil,

During my code review I found several issues regarding formatting in code, e.g. people didn't put tabs correctly, or brackets were not aligned, or there was double enter, or there was no space between package and import lines, or there was no spacing around operators.

I think it would be good to add an article "Java Coding Conventions" and maybe with some simple examples.

Kind regards,
Valentina

**Comment by valentinacupac** [comment]
@ivamil, when closing, please before you close, make a link to the new ticket you had created, like in this way #13, so then we can see where it got continued....

**Comment by ivamil** [comment]
@valentinacupac , ok.

**Comment by ivamil** [comment]
Task is in #13 . Closing idea ticket.
