### ISSUE TITLE
Coding Conventions 

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#13]
Hi @MarijaBircevic ,

During the lessons and homeworks that we have ,the most common mistakes that we made regarding formatting in code are that  people didn't put tabs correctly, or brackets were not aligned, or there was double enter, or there was no space between package and import lines, or there was no spacing around operators.

So, the next task for you is to write an article (Serbian version) "Java Coding Conventions" and maybe with some simple examples.

Is it ok for you?

Kind regards,
Iva

**Comment by MarijaBircevic** [comment]
It’s ok. Thanks.

**Comment by ivamil** [comment]
Evo stranice : 

- https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D0%BD%D1%86%D0%B8%D1%98%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%B0%D1%9A%D0%B0.md

**Comment by ivamil** [comment]
Thank you @MarijaBircevic :)

Done.
Closing task ticket.
