### ISSUE TITLE
Author's Guide - Writing Comments and Version Tracking

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#15]
Hi @ivamil,

Small idea, could you think up of a page to have some procedures regarding writing comments when committing, e.g. instead of just writing that a page was changed, to have short description of what was changed. This I think would be especially useful later when people are doing translations, to be able to track changes.

Maybe this could be an "Author's Guide" page, i.e. a page where you write any procedures that all authors should follow, which includes the above regarding comments as well as rules regarding GitHub tickets and any other procedures.

Kind regards,
Valentina

**Comment by ivamil** [comment]
Done.
Closing idea ticket.
