### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#16]
Hi @ivamil,

Could you also check with the authors who have already started contributing, to ask them to write a short bio about themselves (length = approx one paragraph), where they write their name, their education and/or experience, their interest in IT / technology / programming / software and what their contributions are within Alptium. Both English and Serbian
https://github.com/alptium/alptium.github.io/blob/master/Srpski/o-nama.md
https://github.com/alptium/alptium.github.io/blob/master/English/About-us.md

To avoid merge conflicts in GitHub, I would suggest you make headings on that page with their names, and then assign them tickets. In this way, since they'll be working on different sections within the page, there won't be issues when merging the page.

This will also be a good scenario to use the push and pull approach so that everyone sees how working on one page they get synced together.

Thanks,
Valentina

**Comment by ivamil** [comment]
Done. Closing idea ticket.
