### ISSUE TITLE
Asking Questions Procedure

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#17]
Hi @ivamil,

I was thinking that GitHub tickets could be used for people to ask questions, and then that can be used as additional input for adding further information to the tutorial pages.

So for example, if someone has a question or something isn't clear to them regarding Java, then they could make a new ticket in alptium.github.io with label "question" and choose project "Writing Project" and then write their questions, where I could answer it and then the authors could update their pages or make additional pages.

What do you think about this idea & possible procedure/process for this?

Thanks,
Valentina

**Comment by ivamil** [comment]
@valentinacupac,  I was thinking about the same thing. That will be very useful for everyone. 

Would you like me to inform people about it and to explain them how to do that ?

**Comment by valentinacupac** [comment]
@ivamil, I think there could be a general "Procedures and Processes" page that you could create, and it would have various procedures, such as procedures for asking questions, procedures for writing, and any other procedures.... Then after you make that page, you could give a short overview in a discussion post and provide link to the procedures page. Let me know what you think?

**Comment by ivamil** [comment]
@valentinacupac , ok ,I'll do it.

**Comment by ivamil** [comment]
Hi @valentinacupac ,

I want to inform you that I write a text for 'Processes and Procedures' section about :

1. Git Hub Desktop - Push and Pull instructions
2. Asking questions instructions

Kind regards,
Iva

**Comment by ivamil** [comment]
@valentinacupac ,

I've done the task. Closing idea ticket.
