### ISSUE TITLE
About us page - Sandra Atijas

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#19]
Hi @saki3663 

can you write a short bio about you, (length = approx one paragraph), where you'll write your name, education and/or experience, interest in IT / technology / programming / software and what your contribution is within Alptium. Both English and Serbian version.

https://github.com/alptium/alptium.github.io/blob/master/Srpski/o-nama.md
https://github.com/alptium/alptium.github.io/blob/master/English/About-us.md

Kind regards,
Iva

**Comment by ivamil** [comment]
Hi @saki3663 ,

please write a comment here that you've done  and close the ticket.

Thanks,
Iva

**Comment by saki3663** [comment]
I have done this.
