### ISSUE TITLE
How to write a good CV

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#23]
Hi @ivamil,

Please could you make a section for Recruitment in our main page and create a new page "How to write a CV", then provide tha tpage to @nevenan so that she can write some content. 

This is the first article that @nevenan is writing, so please show her GitHub markdown.

Kind regards,
Valentina

**Comment by ivamil** [comment]
@valentinacupac , ok .

Kind regards,
Iva

**Comment by ivamil** [comment]
Closing task ticket.

**Comment by ivamil** [comment]
#26 Done.
