### ISSUE TITLE
Translation task

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#30]
Hi @saki3663 ,

please can you translate these: 

1. https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%B0-%D0%BB%D0%B8%D0%BD%D0%B8%D1%98%D0%B0.md
2.
https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%91%D0%B0%D0%B7%D0%B8%D1%87%D0%BD%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BA%D0%B5-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%98%D0%B5.md
3
.https://github.com/alptium/alptium.github.io/blob/master/Srpski/ELSE-IF-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%98%D0%B5.md

Here are the links for English version:
1. https://github.com/alptium/alptium.github.io/blob/master/English/Command-Line-IO.md

2. https://github.com/alptium/alptium.github.io/blob/master/English/Basic-mathematical-operators.md

3. https://github.com/alptium/alptium.github.io/blob/master/English/Else-and-If-functions.md

Kind regards,
Iva

**Comment by saki3663** [comment]
Dear @ivamil,

I have done this. I will apply tomorrow. :)

**Comment by ivamil** [comment]
@saki3663 , 

great job :)

I will move your ticket in 'Progress' column but in the future, please you do it because that's what we have to do for easier tracking of tasks.
Thanks a lot :) 

Kind regards,
Iva

**Comment by saki3663** [comment]
Of course:) Just Im now leaving Belgrade for vacancions,and I didn't have
my laptop to do that :)

**Comment by ivamil** [comment]
I wish you a pleasant vacation :)

**Comment by saki3663** [comment]
Dear @ivamil ,

 I have done the task. You can review it.

**Comment by valentinacupac** [comment]
@ivamil, please add in the procedure that for all tickets done, that after you review you will close the ticket.
So that means:
* Author puts ticket into review
* Lead (@ivamil) reviews and puts into closing.

**Comment by ivamil** [comment]
Closing task ticket.
