### ISSUE TITLE
Translation task 

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#33]
Hi @SavovicGoran 

new task for you is to translate page:

https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9F%D0%B8%D1%82%D0%B0%D1%9A%D0%B0-%D0%B8-%D0%BE%D0%B4%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B8.md

Link for English version:

https://github.com/alptium/alptium.github.io/blob/master/English/Questions-and-Answers.md

Kind regards, 
Iva

**Comment by SavovicGoran** [comment]
I'm on it ;)

**Comment by SavovicGoran** [comment]
Done.
 Tacku 5. sam napisao u mnozini posto ima vise polja.

**Comment by ivamil** [comment]
Super, hvala na sugestiji i ispravci  :) 

Jos samo ostavi komentar da si zavrsio zadatak i zatvori tiket.

Pozdrav!

**Comment by SavovicGoran** [comment]
Zavrseno/ Done.
