### ISSUE TITLE
Translation - Loops(English version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#39]

**Comment by ivamil** [comment]
Hi @saki3663 ,

can you translate :

https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9F%D0%B5%D1%82%D1%99%D0%B5-Loops.md

Here is the link for your English version:

https://github.com/alptium/alptium.github.io/blob/master/English/Loops.md

If you find any mistake or have suggestions, please note to me.

Kind regards,
Iva

**Comment by ivamil** [comment]
@saki3663 , jos ovaj prevod. I molim te ako ima potrebe za nekom doradom, ako je nejasno napisano, ili bilo sta drugo, obavesti me jer sto vise citam sve manje mi ima sve smisla. :)

 Hvala :)

**Comment by saki3663** [comment]
Krecem sa ovim prevodom:)

**Comment by saki3663** [comment]
done :)

**Comment by ivamil** [comment]
Great! :)
Done. Closing task ticket.
