### ISSUE TITLE
Translation - Arrays(English version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#40]

**Comment by ivamil** [comment]
Hi @SavovicGoran ,

can you translate:

https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9D%D0%B8%D0%B7%D0%BE%D0%B2%D0%B8-%D0%90rrays.md

Here is the link for your English version: 

https://github.com/alptium/alptium.github.io/blob/master/English/Arrays.md

If you find any mistake or have suggestions, please note to me.

Kind regards,
Iva

**Comment by SavovicGoran** [comment]
I'm on it ;)

**Comment by SavovicGoran** [comment]
Preveo, mislim da ti fali jedna slika, iznad Primer 2 pise samo SLIKA ali nema slike.

**Comment by ivamil** [comment]
@SavovicGoran , 
 
the picture will be inserted afterwards.

Please check line 64 and 68 in text that you write.

Thanks :)

**Comment by SavovicGoran** [comment]
Corrected, tnx  :)
If u see any more mistake please let me know.

**Comment by ivamil** [comment]
Done. Great job, thanks! :)
Closing task ticket.
