### ISSUE TITLE
Translation - Boolean Logic(English version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#41]

**Comment by StubbornMaster** [comment]
Please provide some description.

**Comment by ivamil** [comment]
Hi @saki3663,

can you translate:

https://github.com/alptium/alptium.github.io/blob/master/Srpski/Boolean-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0.md

Here is the link for your English version:

https://github.com/alptium/alptium.github.io/blob/master/English/Boolean-Logic.md

If you find any mistake or have suggestions, please note to me.

Kind regards,
Iva

**Comment by ivamil** [comment]
Done.
Closing task ticket.
