### ISSUE TITLE
Translate - Plan and Program(English version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#42]

**Comment by ivamil** [comment]
Please can you translate:

https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9F%D0%BB%D0%B0%D0%BD-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC.md

Here is the link for your English version:

https://github.com/alptium/alptium.github.io/blob/master/English/Plan-program.md

If you find any mistake or have suggestions, please note to me. 

Kind regards,
Iva

**Comment by SavovicGoran** [comment]
Done.

**Comment by ivamil** [comment]
@SavovicGoran ,

great! Thank you :)

**Comment by ivamil** [comment]
Done. 
Closing task ticket.
