### ISSUE TITLE
Translate - Errors in texts (English version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#46]

**Comment by ivamil** [comment]
Please can you translate :

https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%93%D1%80%D0%B5%D1%88%D0%BA%D0%B5-%D1%83-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D0%B8%D0%BC%D0%B0.md

Here is the the link for your English version:

https://github.com/alptium/alptium.github.io/blob/master/English/Text-Errors.md

If you find any mistake or have suggestions, please note to me.

Kind regards,
Iva

**Comment by saki3663** [comment]
done :)

**Comment by ivamil** [comment]
@saki3663 , 

mozes li da proveris da li je doslo do neke greske. Ja sam oznacila za ovaj tiket @MarkoVu12 , a tebe na druga dva tiketa. 
Da li si dobila dobro obavestenje ili je doslo do neke greske?

**Comment by saki3663** [comment]
Moja greska :D

Izvinjavam se

2018-03-01 22:49 GMT+01:00 ivamil <notifications@github.com>:

**Comment by ivamil** [comment]
Nema problema, onda cu zameniti. Jedan tvoj prevod cu dati sada Marku. :)

**Comment by ivamil** [comment]
Done. Closing task ticket.

**Comment by saki3663** [comment]
Pocela sam sad boolean, nemoj to :)

**Comment by saki3663** [comment]
Jaoj sad sam te zbunila, a i sebe :)

Izvini :(

**Comment by ivamil** [comment]
@saki3663 ,

nije problem, dok se uhodamo svi :) 
Da li si aktivirala notifikacije? Da bi bila sigurna koji je zadatak za tebe, pogledaj u ' Assigned', da li si oznacena, tako ces biti sigurna da je to zadatak za tebe. Ili da mi kazes sta te tacno zbunjuje pa da napravimo uputstvo, mozda i drugi imaju isti problem. :)

**Comment by saki3663** [comment]
Ma sve je razumno, nego ja malo spavam pa sam se pogubila :) Koliko vidim
sve sam prevela sto treba :)

**Comment by ivamil** [comment]
Super onda :)
Jesi, sve si zavrsila.

Pozdrav!
