### ISSUE TITLE
Translate - Author's Guide (English Version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#48]

**Comment by ivamil** [comment]
Hi @saki3663 ,

another task for you :)

Please, translate this text:

- https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%92%D0%BE%D0%B4%D0%B8%D1%87-%D0%B7%D0%B0-%D0%B0%D1%83%D1%82%D0%BE%D1%80%D0%B5.md

Link for your English version:

- https://github.com/alptium/alptium.github.io/blob/master/English/Author's-Guide.md

Kind regards,
Iva

**Comment by saki3663** [comment]
Done!

**Comment by ivamil** [comment]
Great! :)
Closing task ticket.
