### ISSUE TITLE
Test ticket 

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#5]
Hi Valentina this is a test ticket for you to write about some topic

**Comment by valentinacupac** [comment]
Hi @ivamil, instead of writing Valentina, could you write @ and then my name, similar like how I wrote your name. Please try that.

**Comment by valentinacupac** [comment]
Also, please start ticket names with capital letter, i.e. Test ticket, please update.

**Comment by ivamil** [comment]
Hi @valentinacupac , hope it's all right now.

**Comment by ivamil** [comment]
Hi @valentinacupac, this is an example of task ticket that I will send to team members. 

Hi @saki3663 , I'm giving you a task  to translate on English language:

1.  alptium.github.io/Srpski/Uvod.md , and 
2.  alptium.github.io/Srpski/rad-u-Git-Hub.md

If you find any mistake or have  suggestion please note to me. 

Kind regards ,
Iva or @ivamil ?

**Comment by ivamil** [comment]
Or this link?

https://github.com/alptium/alptium.github.io/blob/master/Srpski/rad-u-Git-Hub.md

**Comment by valentinacupac** [comment]
Hi @ivamil, please when making the task for translations, provide also the link to the empty page for the English translation, so that the assignee knows where to write the text.

**Comment by valentinacupac** [comment]
@ivamil, I assume you can now close this test ticket, or do you have any remaining work here?

**Comment by ivamil** [comment]
@valentinacupac, I can close, but I don't have 'close' option for this one:

https://github.com/alptium/iva.milosevic/issues/1

**Comment by valentinacupac** [comment]
@ivamil, there should be a "Close issue" button, but if not, we'll check tomorrow...

**Comment by valentinacupac** [comment]
I closed it now.
