### ISSUE TITLE
Topic listing from previous lessons

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#50]
Providing @ivami with the list of topics / headings from last 2 lessons.

**Comment by valentinacupac** [comment]
Hi @ivamil, I provided list of topics based on previous lessons, see #54, #53, #52, #51.

Please review it and let me know if it's ok or if anything else is needed.

**Comment by ivamil** [comment]
@valentinacupac ,
It's ok. I don't need anything else.

Done.
Closing task ticket.
