### ISSUE TITLE
Lesson Materials 2018-02-14 Object Oriented Programming

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#54]
Hi @ivamil, this was the introductory object oriented programming lesson, I wrote this code:

https://github.com/alptium/valentina.cupac/tree/master/hospital/src/hospital

**Comment by valentinacupac** [comment]
See related ticket #37.

**Comment by valentinacupac** [comment]
Hi @ivamil, the core concepts we covered were:

* Classes
* Attributes
* Methods
* Objects

Then in the code there were practical examples of:
* Non-OOP
* OOP

There was also explanation regarding nouns, verbs, etc. - techniques we use to define classes, attributes and methods, explanation of classes and objects, and also example for hospital, and changing from non-OOP to OOP code.

**Comment by ivamil** [comment]
Done.
Closing preparation ticket.
