### ISSUE TITLE
Setup for T. Golubovic

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#57]
Hi @ivamil,

We will be having a new section for our writing team, leader will be: @TamaraG13.

Could you setup tickets for her for the following topics:
* SDLC
* Agile
* Scrum
* Issue Tracking

When she writes those articles, to reference any websites or materials used in preparing the content.

Thanks,
Valentina

**Comment by ivamil** [comment]
@valentinacupac ,

how to name section for these topics in main Alptium?

**Comment by valentinacupac** [comment]
@ivamil, make a new section called "Project Management"

So we will have

Java Programming
Project Management
Processes and Procedures
etc..

**Comment by ivamil** [comment]
Done. 
Closing task ticket.
