### ISSUE TITLE
Topic - Database Normalization (Serbian Version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#59]

**Comment by saki3663** [comment]
done

**Comment by ivamil** [comment]
Hi @lespabrandzulic82 ,

here is a link for your topic, Serbian version:

- https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%9D%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%98%D0%B0.md

Kind regards,
Iva

**Comment by TamaraG13** [comment]
@saki3663 you can do a final review :)

**Comment by saki3663** [comment]
This is great. Just on the first photo, please check sides of cardinality whether s well written.  @TamaraG13 @ivamil  @lespabrandzulic82

**Comment by ivamil** [comment]
Done. Closing ticket.
