### ISSUE TITLE
Introduction and Working with GitHub - English Translation

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#6]
Hi @saki3663 ,

 I'm giving you a task to translate on English language:

1. https://github.com/alptium/alptium.github.io/blob/master/Srpski/Uvod.md , and
2. https://github.com/alptium/alptium.github.io/blob/master/Srpski/rad-u-Git-Hub.md

Also, here are the links of empty pages for English translation:

1. https://github.com/alptium/alptium.github.io/blob/master/English/Introduction.md
2. https://github.com/alptium/alptium.github.io/blob/master/English/Git-Hub-Use.md

If you find any mistake or have suggestions please note to me.

Kind regards ,
Iva

**Comment by ivamil** [comment]
Cao @saki3663 ,

Radila sam neke izmene u tekstovima pa molim te pogledaj i ispravi. 

Izvini sto ti dodajem sad jos da radis, (a vidim u poruci da si vec zavrsila) ali morala sam da bi se izmene koje sam radila sa Valentinom, uklopile. 

Pozdrav,
Iva

**Comment by saki3663** [comment]
Ok, samo ako nije problem, reci mi gde ja kacim prevd.. malo sam se zbunila

2018-02-05 17:29 GMT+01:00 ivamil <notifications@github.com>:

**Comment by saki3663** [comment]
Dear @ivamil ,

I have finished the introduction. Soon, I will put the rest.

If you have any suggestions or changes, please let me know.

**Comment by ivamil** [comment]
Hi @saki3663 , 

It's ok, but can you check the Serbian version 'cause I make some changes. Its basically the same text but I change the order and few sentences.
We will occasionally make small changes in text and appearance in order to improve our work.

I hope its ok for you. 

P.S. Please when you finish translation, move your ticket in 'Review' column.

Thanks a lot :)

Kind regards,
Iva

**Comment by saki3663** [comment]
Yeah, its fine for me. Just I didnt understand.. Should I change something
or you will?

Thanks for response

**Comment by ivamil** [comment]
Yes , you do the changes in your English version based on changes in Serbian version. 

You're welcome.

**Comment by saki3663** [comment]
I have put now there :)

**Comment by saki3663** [comment]
If you need some more change, please write me exactly what.

Regards

**Comment by ivamil** [comment]
Great job! 

Thanks a lot :)

Kind regards,
Iva

**Comment by ivamil** [comment]
Closing task ticket.
