### ISSUE TITLE
Topic - Database Relationships (Serbian Version)

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#60]

**Comment by saki3663** [comment]
done

**Comment by lespabrandzulic82** [comment]
@ivamil , i have created document for relation database, in serbian. Please check is there any to change or to add.

**Comment by saki3663** [comment]
I think I should check ;)

**Comment by lespabrandzulic82** [comment]
@saki3663 , ok :) .

**Comment by ivamil** [comment]
@saki3663 ,

check this topic and inform me when its done so I can forward the topic for translation.

Kind regards,
Iva

**Comment by saki3663** [comment]
I thnk this is quite good @lespabrandzulic82 :)

**Comment by TamaraG13** [comment]
@saki3663 you can do a final review :)

**Comment by lespabrandzulic82** [comment]
@ivamil I have added code samples. Could you take a look? Thanks.

**Comment by ivamil** [comment]
@lespabrandzulic82 ,

great job, brief, clear, concise and understandable :)

**Comment by ivamil** [comment]
Done. 
Closing task ticket.
