### ISSUE TITLE
Review Support 

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#63]
Hi @saki3663 ,

we have a new author in the team, @lespabrandzulic82 , and your future task will be to review his topics along with me.  :)

Kind regards,
Iva

**Comment by saki3663** [comment]
If I understand well, this means that the text from lectures I need as well to check with you? :)

**Comment by ivamil** [comment]
You check texts that Branko Spalovic writes. Now I will assigne you in his task tickets so that you can follow his proress. :)
So, is it ok for you?

**Comment by ivamil** [comment]
@saki3663 ,

 please, can you check the main Alptium and help me with Serbian translation on topics where I put a question mark ?

- https://github.com/alptium/alptium.github.io/blob/master/README.md

Thanks :)

**Comment by saki3663** [comment]
I have to write something in Serbian? I didn't undestand well

**Comment by ivamil** [comment]
Da , da mi pomognes oko prevoda ovih naslova koji su na engleskom jeziku, a pored kojih sam stavila znak pitanja. Ukoliko i ti nisi sigurna za prevode ovih naslova, pitacemo Branka, ipak su to njegove teme.

Ujedno proveri sve naslove na srpskom jeziku i ako imas neki predlog za adekvatnije imenovanje naslova, slobodno mi ovde napisi.

Hvala :)

**Comment by saki3663** [comment]
Znaci naslovi da se prevedu :) To je ok, pogledacu. Mislim samo da neke
stvari bas ne moze na srpski da se prevedu

**Comment by ivamil** [comment]
Da, pogledaj srpske  naslove na osnovu naslova koji su na engleskom jeziku, oni su sigurni :)

Hvala :)

**Comment by ivamil** [comment]
@saki3663 ,

E super, vidim da si prevela one naslove, hvala puno na pomoci. :)
Sad samo da ti objasnim u vezi tiketa. One tikete koje si prebacila na pregled, oni se odnose na zadatak koji treba Branko da odradi, zato je u tim tiketima on oznacen, ti si oznacena zato sto ces raditi preglede tih zadataka. 
Kad on objavi komentarom u okviru tiketa da je zavrsio zadatak, tek tada ti pregledas i prebacis u onu Review kolonu. Valentina me je naknadno obavestila da ce ona posle obaviti definitivan pregled tih radova. 
Ukoliko bude nekih izmena, obavesticu te. :)

**Comment by saki3663** [comment]
Vazi, hvala na pojasnjenju :)

**Comment by ivamil** [comment]
Nema na cemu :)
Done. Closing support ticket.

**Comment by ivamil** [comment]
E ovako, ti radis pregled Brankovih tiketa, odnosno radova. Kad bude zavrsio sa zadatkom, prenece tiket/tikete u In Review (Additional Content) kolonu. Onda  ces ti raditi pregled i ukoliko je dobro zatvoris tiket, a ukoliko nije, das smernice, sugestije. 
Ako postoji nesto gde ti nisi sigurna, obratis se Valentini da ona odradi pregled i to je to.

Ako ti treba bilo kakva pomoc dok se uhodas, tu sam :)

**Comment by saki3663** [comment]
Vazi.

Nadam se samo da ce mi stici mail kaf on zavrsi i gde da gledam :)

**Comment by ivamil** [comment]
Lakse ti je da podesis da ti stizu notifikacije ovde. Meni je preko maila malo konfuzno a i primetila sam da kasne obavestenja. Ovde ti je sigurnije. :)

-https://github.com/alptium/alptium.github.io/blob/master/Srpski/Git-Hub-%D0%BE%D0%B1%D0%B0%D0%B2%D0%B5%D1%88%D1%82%D0%B5%D1%9A%D0%B0.md

**Comment by ivamil** [comment]
Done.
Closing support ticket.
