### ISSUE TITLE
Program installing and Installing Eclipse Hello World - English Translation

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#7]
Hi @SavovicGoran ,

 I'm giving you a task to translate on English language:

1. https://github.com/alptium/alptium.github.io/blob/master/Srpski/pokretanje.md ,and
2. https://github.com/alptium/alptium.github.io/blob/master/Srpski/instalacija.md

Also, here are the links of empty pages for English translation:

1. https://github.com/alptium/alptium.github.io/blob/master/English/Installing-Eclipse-Hello-World.md ,and
2. https://github.com/alptium/alptium.github.io/blob/master/English/Program-installing.md

If you find any mistake or have suggestions please note to me.

Kind regards ,
Iva

**Comment by SavovicGoran** [comment]
Gotovo, nadam se da je ok. Ako ima nekih gresaka please let me know ;)

**Comment by ivamil** [comment]
Ово је било брзо,свака част 👍 

Само си заменио, текст за инсталирање програма си поставио у Installing-Eclipse-Hello-World.md, и обрнуто. Само то исправи и супер што си објаснио значење 'Static' i 'Void' :)

**Comment by saki3663** [comment]
Ljudiii krecem sa prvodom od sutra :)

2018-02-04 11:22 GMT+01:00 ivamil <notifications@github.com>:

**Comment by ivamil** [comment]
Cao @SavovicGoran ,

Morala sam da uradim neke izmene da bi imalo sve vise smisla. Zato te molim da proveris te izmene jer verovatno ces imati dodatnog posla oko prevoda. 

1. https://github.com/alptium/alptium.github.io/blob/master/Srpski/pokretanje.md
2. https://github.com/alptium/alptium.github.io/blob/master/Srpski/instalacija.md

Naravno linkovi za prevod ostaju isti:

1. https://github.com/alptium/alptium.github.io/blob/master/English/Installing-Eclipse-Hello-World.md
2. https://github.com/alptium/alptium.github.io/blob/master/English/Program-installing.md

Pozdrav,
Iva

**Comment by saki3663** [comment]
Dragi svi,

Ja sam prevela ovo na poslu (imala sam malo vremena) Samo da dodjem kuci i
stavljam na git hub

**Comment by SavovicGoran** [comment]
Ja sam od srede 100% dostupan, do tada cu nadam se zavrsiti sve obaveze koje sam isplanirao da zavrsim vezane za moju svadbu :) verujte mi da ne znam gde bijem poslednjih 7 dana....

**Comment by saki3663** [comment]
Jel smo pozvani na svadbu?

**Comment by SavovicGoran** [comment]
Vala ako sve zavrsim na vreme i kako sam planirao jeste :) ;)

2018-02-05 17:50 GMT+01:00 saki3663 <notifications@github.com>:

> Jel smo pozvani na svadbu?
>

**Comment by saki3663** [comment]
Hhahh uzivaj tu u priprrmama za svadbu ako treba ja mogu nesto da predvedem
:)

**Comment by ivamil** [comment]
Ooo lepe vesti :)  Uzivaj u pripremama :) 

Nije frka stvarno, ja tek treba da pisem tekstove za drugi cas, tako da imate vremena. 

Pozdrav :)

**Comment by ivamil** [comment]
@SavovicGoran,

mozes li da proveris samo ove linkove koje sam ti postavila gore u prvoj poruci? Zamenio si tekstove, videces kad uporedis srpsku i englesku verziju a i radili smo male izmene teksta.

Pozdrav!

**Comment by ivamil** [comment]
Hi @SavovicGoran ,

did you see the last comment in this ticket?

**Comment by SavovicGoran** [comment]
Evo sad cu da proverim.

**Comment by SavovicGoran** [comment]
@ivamil sredjena je permutacija i editovani linkovi sa rednim brojem 1. Sto se tice linka br 2 vidim da je skroz promenjen, da i ja tako uradim?

**Comment by ivamil** [comment]
@SavovicGoran 

da , isto tako i ti izmeni.

**Comment by SavovicGoran** [comment]
ok

**Comment by SavovicGoran** [comment]
@ivamil I've added new changes to already existing file. Is that ok?

**Comment by ivamil** [comment]
@SavovicGoran ,

It's ok. Thanks :)

Done. Closing task ticket.
