### ISSUE TITLE
Procedural Update

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#70]
Hi @ivamil, we now have two types of content:
* Content from lessons - you continuing reviewing it
* Additional content, which was not in the lessons - these topics I could review

This can be seen in the 2 review columns here https://github.com/orgs/alptium/projects/2

So then in the procedures could you update this, and I will explain it to everyone during the next lesson, since now we're expanding the range of the content.

**Comment by ivamil** [comment]
Ok, I'm on it.

**Comment by ivamil** [comment]
@valentinacupac ,

Done.
- https://github.com/alptium/alptium.github.io/blob/master/Srpski/%D0%92%D0%BE%D0%B4%D0%B8%D1%87-%D0%B7%D0%B0-%D0%B0%D1%83%D1%82%D0%BE%D1%80%D0%B5.md

Is it ok?

**Comment by ivamil** [comment]
Done. 
Closing idea ticket.
