### ISSUE TITLE
Program Installation - Serbian Version

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#8]
Hi @MarijaBircevic ,

task for you is to write a text about 'Instalacija Git Hub Desktop programa' Serbian version, just add it below the existing text.

Here is the link for Serbian version:

-> https://github.com/alptium/alptium.github.io/blob/master/Srpski/instalacija.md

If you find any mistake or have suggestions please note to me.

Kind regards ,
Iva

**Comment by MarijaBircevic** [comment]
Hello, :)
I need your help. Honestly, I'm not sure what to do: (
Do I just need to check the text on the link or need to write a new text?
On the link you sent me is Java and Eclipse instalation, and my task
is   'Instalacija
Git Hub Desktop programa' .
Can you explain to me what I should do or should I write to Valentina?
Thank you!

**Comment by ivamil** [comment]
Cao @MarijaBircevic ,

ja sam napisala tekst za instalaciju Java i Eclipse, sada ti u nastavku pises korake za instalaciju Git Hub desktop programa. 
Ja sam to radila na primer na osnovu you tube snimka koje nam  je Valentina dala na mail-u. 
Naravno ako uocis bilo kakvu gresku u mom pisanju ili imas neki predlog ,slobodno mi javi. 

Nadam se da sam ti pomogla. Ako imas jos pitanja,tu sam :)

Pozdrav,
Iva

**Comment by MarijaBircevic** [comment]
Ok, mislim da sam uspela. :) Ukoliko misliš da su mi slike prevelike, mogu da ih korigujem. Hvala.

**Comment by ivamil** [comment]
Све је супер :)

**Comment by ivamil** [comment]
Closing task ticket.
