### ISSUE TITLE
Including T. Golubovic in Advanced Topics Review / Questions asking

### ISSUE THREAD

**Issue by valentinacupac** [alptium/alptium.github.io#83]
Hi @ivamil,

Regarding articles written by @lespabrandzulic82, which are currently being reviewed by @saki3663, I would also like to add one more person in the review - @TamaraG13 - her role in the the review should be when reading the article, trying to see what questions she has, based on reading those articles, since during our lessons, @TamaraG13 was good at coming up with questions.

Kind regards,
Valentina

P.S. Regarding the additional research content being written by @lespabrandzulic82, one review comment from my side is: each of those articles should have some sample code. Currently when I saw the articles, the theory part was good, but the practical part (i.e. code samples) is missing, so please could you organize for that to be included.

**Comment by ivamil** [comment]
Done.
Closing idea ticket.
