### ISSUE TITLE
New review member - Additional Content

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#87]
Hi @TamaraG13

your task from now on is to review additional contents with @saki3663 . I will assign you in task tickets and when the ticket is moved in review column, your task is to check it, if you have any question ask author within a ticket or if you don't have a question or suggestion, just write a note to @saki3663 (within a task ticket) so that she can do a final review.

If you have any question, please note to me.  Also, if it is ok for you please note to me here.

Kind regards,
Iva

**Comment by TamaraG13** [comment]
Hi @ivamil  thank you for detailed explanation, everything is alright :)

**Comment by ivamil** [comment]
@TamaraG13 , 

great, now I will assigne you. :)

**Comment by ivamil** [comment]
Done.
Closing support ticket.
