### ISSUE TITLE
Markdown упутство 

### ISSUE THREAD

**Issue by ivamil** [alptium/alptium.github.io#9]
Здравo @alptium/technical-writing-team ,

 написаћу вам упутства за писање текстова. 

1. Користите Notepad програм за писање текстова који ћете отворити у оквиру Git Hub -> alptium.github.io фолдера на вашем рачунару. 

2. Именујте га и сачувајте у .md формату, то би изгледало овако на пример: назив фајла.md

3. Они који пишу на српском језику нека користе ћирилично писмо.

4.Како да убацујете фотографије, болдујете, убацујете кодове из Eclipse програма итд, пронаћићете на страници: 
https://guides.github.com/features/mastering-markdown/

5. Овде ћу приказати пример за слику. Прво сам са Markdown прекопирала код за фотографије који изгледа овако:

![GitHub Logo](/images/logo.png)

![proizvoljni opis slike](/naziv foldera u kom se slika nalazi/naziv slike.format)

Водите рачуна да буде тачно написано,поштујте размаке ,велика слова и остале компоненте које постоје.

6. Може се десити да Git Hub не препозна размаке код на пример назива фајлова, мени се то десило код назива Notepad фајлова, али на пример препозна уколико измећу речи уместо размака ставим цртице - .

7. Када будете писали примере кодова из Еклипсе, уместо screenshot-ова ,писаћете овај знак ``` на почетку и на крају кода.
То је као коси наводник који се налази у оквиру тастера у горњем левом углу тастатуре.

**Comment by ivamil** [comment]
Исправићу грешку, ово иде у 'Writing Team' ,а не у 'Technical writing team'.

**Comment by MarijaBircevic** [comment]
Hvala. sada ću da završim. :)

**Comment by valentinacupac** [comment]
Hi @ivamil, I think this could be added to the new "Procedures and Processes" page.

**Comment by ivamil** [comment]
Done. I added this in "Procedures and Processes" page, Serbian version, and I will give someone a task to translate it. Closing this ticket.
